# Generated by Django 4.0.3 on 2022-04-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_page_settings', '0003_alter_user_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='static/user_profile_page_settings/profileImages/'),
        ),
    ]
