# Generated by Django 4.0.3 on 2022-04-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_page_settings', '0004_alter_user_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backroundImage',
            field=models.ImageField(blank=True, null=True, upload_to='static/user_profile_page_settings/profileImages/'),
        ),
    ]
