# Generated by Django 4.0.3 on 2022-04-28 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_page_settings', '0005_user_backroundimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='backroundImage',
            new_name='backgroundImage',
        ),
    ]
