# Generated by Django 4.0.3 on 2022-03-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('userJobTitle', models.CharField(max_length=100)),
                ('userDescription', models.CharField(max_length=250)),
                ('userImage', models.ImageField(upload_to='main_app/images/')),
                ('userFaceBookUrl', models.URLField(blank=True)),
                ('userDribbleUrl', models.URLField(blank=True)),
                ('userInstagramUrl', models.URLField(blank=True)),
                ('userLinkedInUrl', models.URLField(blank=True)),
                ('userGoogleUrl', models.URLField(blank=True)),
            ],
        ),
    ]
