# Generated by Django 4.0.3 on 2022-04-18 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
