# Generated by Django 4.0.3 on 2022-04-18 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_page_settings', '0005_user_backroundimage'),
        ('home_page', '0005_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=280)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile_page_settings.user')),
                ('replyTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_page.comments')),
            ],
        ),
    ]
