# Generated by Django 4.0.3 on 2022-04-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_post_postlikes_postdislikes_comments_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, upload_to='static/home_page/post_content'),
        ),
    ]
