# Generated by Django 4.0.3 on 2022-04-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_alter_post_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdislikes',
            old_name='postId',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postdislikes',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='postlikes',
            old_name='postId',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postlikes',
            old_name='userId',
            new_name='user',
        ),
    ]
