# Generated by Django 4.0.3 on 2022-04-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0010_rename_postid_postdislikes_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdislikes',
            old_name='post',
            new_name='postId',
        ),
        migrations.RenameField(
            model_name='postdislikes',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='postlikes',
            old_name='post',
            new_name='postId',
        ),
        migrations.RenameField(
            model_name='postlikes',
            old_name='user',
            new_name='userId',
        ),
    ]
