# Generated by Django 4.0.3 on 2022-04-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0011_rename_post_postdislikes_postid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blogContent',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='blogImage',
            field=models.ImageField(blank=True, null=True, upload_to='static/user_profile_page_settings/profileImages/'),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Question', 'Question'), ('Multimedia', 'Multimedia'), ('Blog', 'Blog'), ('Questionnaire', 'Questionnaire')], default='Question', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
