# Generated by Django 4.0.3 on 2022-04-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0013_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static/home_page/post_content/'),
        ),
    ]
