# Generated by Django 4.0.3 on 2022-05-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_page_settings', '0006_rename_backroundimage_user_backgroundimage'),
        ('home_page', '0014_alter_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdislikes',
            name='postId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dis_likes', to='home_page.post'),
        ),
        migrations.RemoveField(
            model_name='postdislikes',
            name='userId',
        ),
        migrations.AddField(
            model_name='postdislikes',
            name='userId',
            field=models.ManyToManyField(related_name='post_dis_likes', to='user_profile_page_settings.user'),
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='postId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='home_page.post'),
        ),
        migrations.RemoveField(
            model_name='postlikes',
            name='userId',
        ),
        migrations.AddField(
            model_name='postlikes',
            name='userId',
            field=models.ManyToManyField(related_name='post_likes', to='user_profile_page_settings.user'),
        ),
    ]
